### ISSUE TITLE
Uncaught exception when trying to decode time

### ISSUE THREAD

**Issue by evonreis** [ligovirgo/seismon#13]
```
 Traceback (most recent call last):                                                        
   File "/var/lib/seismon/seismon/seismon/models.py", line 918, in <module>                
     run_seismon(purge=args.purge, init_db=args.init_db)                                   
   File "/var/lib/seismon/seismon/seismon/models.py", line 811, in run_seismon             
     ingest_earthquakes(config, args.lookback)                                             
   File "/var/lib/seismon/seismon/seismon/models.py", line 758, in ingest_earthquakes      
     attributeDic = eqmon.read_quakeml(quakemlfile,eventName)                              
   File "/var/lib/seismon/seismon/seismon/eqmon.py", line 1689, in read_quakeml            
     dt = datetime.strptime(timeString, "%Y-%m-%d %H:%M:%S.%f")                            
   File "/var/opt/conda/base/envs/seismon/lib/python3.10/_strptime.py", line 568, in _strp>
     tt, fraction, gmtoff_fraction = _strptime(data_string, format)                        
   File "/var/opt/conda/base/envs/seismon/lib/python3.10/_strptime.py", line 349, in _strp>
     raise ValueError("time data %r does not match format %r" %                            
 ValueError: time data '2024-11-04 16:41:13' does not match format '%Y-%m-%d %H:%M:%S.%f'  
```

**Comment by mcoughlin** [comment]
@evonreis Maybe could add a try except where you see if the milliseconds is included or not?

**Comment by evonreis** [comment]
Yes, I've done that in another branch.  I'll make a PR.
