### ISSUE TITLE
Crash in ingest_earthquakes from module models.py

### ISSUE THREAD

**Issue by narnaud1974** [ligovirgo/seismon#4]
@mcoughlin & @Nikhil-Mukund 
First crash at EGO:

```
Traceback (most recent call last):
  File "models.py", line 536, in <module>
    run_seismon(purge=args.purge, init_db=args.init_db)
  File "models.py", line 474, in run_seismon
    ingest_earthquakes(config, args.lookback, repeat=True)
  File "models.py", line 433, in ingest_earthquakes
    f = open(os.path.join(timeFolder,"eqxml.txt"),"w")
FileNotFoundError: [Errno 2] No such file or directory: '/data/seismon/ProductClient/data/receiver_storage/origin/ci39924776/ci/1622977719760/eqxml.txt'
```

The actual line is https://github.com/gwdetchar/seismon/blob/c7e2e92ddeecac5035a62d4e2f098808ca126d6c/seismon/models.py#L589.

I don't know what caused the problem -- disappearance of the ````timeFolder````directory or glitch in the file system or ??? --, nor how you would like to protect that command.

**Comment by mcoughlin** [comment]
@narnaud1974 And what happens if you simply restart? Did that directory... disappear?

**Comment by narnaud1974** [comment]
How to restart seismon was my next question... I assume I should not use "--init_db" anymore right!? Or what happens if I do?

About the crash I only noticed it after some time => USGS had already cleaned its old data and so that event was not there anymore.

**Comment by mcoughlin** [comment]
Yes you just remove --init_db from the flag. Init_db wipes the DB and recreates all the tables.
